### ISSUE TITLE
kustomize replacements

### ISSUE THREAD

**Issue by mondaydarknight** [mondaydarknight/k8s-thumbor#1]
```yaml
replacements:
  - source:
      kind: Secret
      name: cdn-thumbor-secret
      fieldPath: data.SSL_CERT
    targets:
      - select:
          kind: Ingress
        fieldPaths:
          - metadata.annotations.[ingress.gcp.kubernetes.io/pre-shared-cert]
        options:
          create: true

```
